version: "3"

services:
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    volumes:
      - ../docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=users, stocks
    restart: always
  api:
    image: "apiusers:v1"
    ports:
      - 8081:8081
    environment:
      DB_URL: jdbc:postgresql://database:5432/users
    restart: always
  apistocks:
    image: "apistocks:v1"
    ports:
      - 8083:8083
    environment:
      DB_URL: jdbc:postgresql://database:5432/stocks
    restart: always